language: java

# required to use Travis' Cassandra service
# https://docs.travis-ci.com/user/database-setup/#cassandra
sudo: required

addons:
  sonarcloud:
    organization: trellis-ldp

cache:
  directories:
    - $HOME/.m2/repository

env:
  - JAVA_OPTS="-Xmx3096m"

matrix:
  fast_finish: true

  include:
    - jdk: openjdk8
    # Cassandra's nodetool does not work on jdk11
    #- jdk: openjdk11

  allow_failures:
    - jdk: openjdk11
    
# install Casssandra "manually" to ensure the presence of nodetool
before_install:
  - echo "deb http://www.apache.org/dist/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install cassandra
  - sudo service cassandra start 

addons:
  apt:
    update: true

install: mvn --quiet -Dcargo.maven.skip -Dcassandra.skip -DskipTests install

# load our schema
before_script: src/test/resources/load.sh

# build
# turn off Cassandra Maven plugin to use Travis' service instead
# skip integration tests b/c travis can't seem to handle them
script: mvn -Dcassandra.skip -Dcassandra.nativeTransportPort=9042 -pl '!integration-tests' install

# in case of failure, spew reports
after_failure:
  - cat impl/target/*-reports/*.txt
  - cat webapp/target/*-reports/*.txt
  - cat integration-tests/target/*-reports/*.txt
  - cat impl/target/logs/system.log
  - cat webapp/target/logs/system.log
  - cat integration-tests/target/logs/system.log
