language: java

addons:
  sonarcloud:
    organization: trellis-ldp

services:
  - cassandra
  
matrix:
  fast_finish: true

  include:
    # JDK 8
    - jdk: oraclejdk8

    # JDK 10
    - jdk: openjdk10

    # JDK 11
    - jdk: oraclejdk11

  allow_failures:
    - jdk: oraclejdk11
    - jdk: openjdk10


script: mvn -Dcassandra.nativeTransportPort=9042 clean install

