language: java

# required to use Travis' Cassandra service
# https://docs.travis-ci.com/user/database-setup/#cassandra
sudo: required

addons:
  sonarcloud:
    organization: trellis-ldp

services:
  - cassandra
  
matrix:
  fast_finish: true

  include:
    # JDK 8
    - jdk: oraclejdk8

    # JDK 10
    - jdk: openjdk10

    # JDK 11
    - jdk: oraclejdk11

  allow_failures:
    - jdk: oraclejdk11
    - jdk: openjdk10

# do not resolve dependencies because webapp depends on impl
install: true

# load our schema
before_script: src/test/resources/load.sh

# turn off Cassandra Maven plugin to use Travis' service instead
script: mvn -P-self-cassandra -Dcassandra.contactHost=localhost -Dcassandra.nativeTransportPort=9042 install

# in case of failure, spew reports
after_failure:
  - cat target/*-reports/*.txt
  - cat impl/target/*-reports/*.txt
  - cat webapp/target/*-reports/*.txt
