language: java

# required to use Travis' Cassandra service
# https://docs.travis-ci.com/user/database-setup/#cassandra
sudo: required

addons:
  sonarcloud:
    organization: trellis-ldp

services:
  - cassandra

cache:
  directories:
    - $HOME/.m2/repository

matrix:
  fast_finish: true

  include:
    # JDK 8
    - jdk: oraclejdk8

    # JDK 11
    - jdk: oraclejdk11

  allow_failures:
    - jdk: oraclejdk11

install: mvn --quiet -Dcassandra.skip -DskipTests install

# load our schema
before_script: src/test/resources/load.sh

# build
# turn off Cassandra Maven plugin to use Travis' service instead
script: mvn -Dcassandra.skip -Dcassandra.nativeTransportPort=9042 install

# in case of failure, spew reports
after_failure:
  - cat impl/target/*-reports/*.txt
  - cat webapp/target/*-reports/*.txt
  - cat integration-tests/target/*-reports/*.txt
  - cat impl/target/logs/system.log
  - cat webapp/target/logs/system.log
  - cat integration-tests/target/logs/system.log
