version: "3"
# https://forums.docker.com/t/cassandra-on-docker-swarm/27923/3 - placement ideas
# https://github.com/thelastpickle/docker-cassandra-bootstrap - monitoring/grafana, other docker details
services:
  trellis-cassandra:
    image: trellisldp/trellis-cassandra:0.8.1-SNAPSHOT
    environment:
      - CASSANDRA_CONTACT_ADDRESS="cassandra-1"
      - CASSANDRA_CONTACT_PORT=9042
      - CASSANDRA_MAX_CHUNK_SIZE=1048576
      #- CASSANDRA_BINARY_READ_CONSISTENCY="ConsistencyLevel.ONE"
      #- CASSANDRA_BINARY_WRITE_CONSISTENCY="ConsistencyLevel.ONE"
      - TRELLIS_JMS_USE_QUEUE="false"
      - TRELLIS_JMS_QUEUE_NAME="trellis"
      - TRELLIS_JMS_URL="tcp://activemq:61616"
    volumes:
      - ./users.auth:/etc/users.auth
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 20
        window: 120s
    links:
      - cassandra-1
      - cassandra-2
      - cassandra-3
      - activemq
    depends_on:
      - cassandra-1
      - cassandra-2
      - cassandra-3
      - activemq
  activemq:
    image: rmohr/activemq:latest
    ports:
      - "61616:61616"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20
        window: 120s
  nginx:
    image: nginx:latest
    container_name: protected_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
      - 8443:443
  cassandra-1:
    image: cassandra
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-1
    links:
      - cassandra-2
      - cassandra-3
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
  cassandra-2:
    image: cassandra
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-2
      CASSANDRA_SEEDS: cassandra-1
    links:
      - cassandra-1
      - cassandra-3
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    depends_on:
      - cassandra-1
  cassandra-3:
    image: cassandra
    environment:
      CASSANDRA_BROADCAST_ADDRESS: cassandra-3
      CASSANDRA_SEEDS: cassandra-1
    links:
      - cassandra-1
      - cassandra-2
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    depends_on:
      - cassandra-2
  cassandra-init:
    image: trellisldp/trellis-cassandra-init:0.8.1-SNAPSHOT
    depends_on:
      - cassandra-3
    links:
      - cassandra-1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
    command: cqlsh cassandra-1 -f /load.cql
