version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
      environment:
        MAVEN_OPTS: -Xmx2048m
    - image: circleci/cassandra:3.10
      environment:
        MAX_HEAP_SIZE: 1024M
        HEAP_NEWSIZE: 512M
    working_directory: ~/trellis-cassandra

    steps:
    - checkout
    - run: 
        name: Install Cassandra for nodetool and cqlsh
        command: |
          sudo sh -c "echo 'deb http://www.apache.org/dist/cassandra/debian 311x main' >> /etc/apt/sources.list"  
          sudo apt-get update
          curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
          sudo apt-get --allow-unauthenticated install cassandra-tools
    - run:
        name: Load Cassandra schema
        command: sh src/test/resources/load.sh
#    - run: 
#        name: Install Maven < 3.6.0 (https://issues.jboss.org/browse/THORN-2229)
#        command: |
#          sudo apt-get remove maven
#          sudo apt-get install maven=3.3.9-4
#          export PATH=/usr/bin:$PATH
#          mvn -v
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn go-offline:resolve-dependencies
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: export PATH=/usr/bin:$PATH ; mvn -Dcassandra.skip -Dcassandra.nativeTransportPort=9042 install
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*txt" -exec cp {} ~/junit/ \;
          find . -type f -regex ".*/target/failsafe-reports/.*txt" -exec cp {} ~/junit/ \;
        when: always
    - run: 
        name: Upload Sonar info
        command: mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN
        when: on_success
    - run:
        name: Spool test results 
        command: find ~/junit -name *.txt | xargs cat
        when: on_fail
    - run:
        name: Spool logs
        command: find . -type f -name "system.log" | xargs cat
        when: on_fail
    - run:
        name: Spool itest logs 
        command: cat integration-tests/target/system.log
        when: on_fail
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit



