version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    - image: cassandra:3.11
      environment:
        MAVEN_OPTS: -Xmx2048m
        MAX_HEAP_SIZE: 2048m
        HEAP_NEWSIZE: 256m
    working_directory: ~/$CIRCLE_PROJECT_REPONAME

    steps:
    - checkout
    - run:
        name: Load C* schema
        command: sh src/test/resources/load.sh
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn go-offline:resolve-dependencies
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn -Dcassandra.skip -Dcassandra.nativeTransportPort=9042 install
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit 
    - run: ls ~/junit | xargs cat


