version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/cassandra:3.10
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn go-offline:resolve-dependencies
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn install
    - run:
        name: Spew test results
        command: find . -type f -path '**/surefire-reports/*.txt' -exec cat {} \; \
                 find . -type f -path '**/failsafe-report/*.txt' -exec cat {} \;
        when: always